version: '3'
services:

  #PHP Service
  app:
    image: engboustani/ticket
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./config/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/

  #MySQL Service
  db:
    image: mariadb:latest
    container_name: db
    hostname: db
    restart: unless-stopped
    tty: true
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: chakavak
      MYSQL_ROOT_PASSWORD: mandegar
      MYSQL_USER: chakavak
      MYSQL_PASSWORD: mandegar
    networks:
      - app-network
    volumes:
      - dbdata:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/my.cnf

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local